---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elasticsearch
  - src: git@github.com:beletsky/netology-ansible-role-kibana.git
    scm: git
    version: "1.0.0"
    name: kibana
  - src: git@github.com:beletsky/netology-ansible-role-filebeat.git
    scm: git
    version: "1.0.0"
    name: filebeat
