---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  containers:
  - name: security-context-demo
    image: fedora:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "trap : TERM INT; sleep infinity & wait" ]
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
