apiVersion: v1
kind: Pod
metadata:
  name: pod-with-common-volume
spec:
  containers:
    - name: backend
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/static"
          name: static-content
    - name: frontend
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/public/content"
          name: static-content
  volumes:
    - name: static-content
      emptyDir: {}
---
