apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:  
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    env:
      - name: NGINX_DOMAIN
        valueFrom:
          configMapKeyRef:
            name: domain
            key: name
            optional: false
  volumes:
  - name: config
    configMap:
      name: nginx-config
