apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-content
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
